#!/bin/bash

BASE_DIR=$( cd "$( echo "${BASH_SOURCE[0]%/*}/.." )" && pwd )
source ${BASE_DIR}/../scripts/common

rpi::cluster::docker-swarm::docker-engine::build(){
  rpi::cluster::docker-swarm::common::log-step "nothing to do"
}

rpi::cluster::docker-swarm::docker-engine::install(){
  rpi::cluster::docker-swarm::common::log-step "Stop Docker Service"
  systemctl stop docker.service docker.socket

  rpi::cluster::docker-swarm::common::log-step "Uninstall 'old' Docker"
  apt-get remove docker-hypriot -y -qq

  rpi::cluster::docker-swarm::common::log-step "Install 'new' Docker"
  dpkg -i ${BASE_DIR}/docker-engine_1.12.0~dev~git20160720.182418.0.a9ca19f-0~jessie_armhf.deb > /dev/null

  rpi::cluster::docker-swarm::common::log-step "Start Docker Service"
  systemctl daemon-reload
  systemctl start docker.socket docker.service
}


rpi::cluster::docker-swarm::docker-engine::clean(){
  rpi::cluster::docker-swarm::common::log-step "nothing to do"
}
