#!/bin/bash

YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

function rpi::cluster::docker-swarm::common::check-root(){
  if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 1>&2
    exit 1
  fi
}

function rpi::cluster::docker-swarm::common::install(){
  rpi::cluster::docker-swarm::common::log-step "Update System"
  apt-get update -y -qq

  rpi::cluster::docker-swarm::common::log-step "General Utilities"
  apt-get install vim make gcc ntp -y -qq

  rpi::cluster::docker-swarm::common::log-step "Reconfigure Timezone"
  timedatectl set-timezone Europe/Zurich

  rpi::cluster::docker-swarm::common::log-step "Set Boot Options"
  if [[ -z $(grep "cgroup_enable=cpuset" /boot/cmdline.txt) ]]; then
    sed -e "s@cgroup_enable=memory@cgroup_enable=memory cgroup_enable=cpuset@" -i /boot/cmdline.txt
  fi
}

function rpi::cluster::docker-swarm::common::log-header(){
  printf "\n%s\n" "$@" 
}

function rpi::cluster::docker-swarm::common::log-step(){
  printf "%s %s\n" "-" "$@" 
}

function rpi::cluster::docker-swarm::common::log-step-warn(){
  printf "%s ${YELLOW}%s${NC}\n" "-" "$@" 
}

function rpi::cluster::docker-swarm::common::log-step-err(){
  printf "%s ${RED}%s${NC}\n" "-" "$@" 
}

function rpi::cluster::docker-swarm::common::log-empty-line(){
  printf "\n"
}

